# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'UiMain.ui'
# Created by: PyQt5 UI code generator 5.15.9
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1450, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ui_imgs/icons/目标检测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 设置主布局
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        
        # 添加标签页控件
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        # 设置标签页最小宽度
        tab_bar = self.tabWidget.tabBar()
        tab_bar.setMinimumWidth(100)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        
        # 检测标签页
        self.tab_detect = QtWidgets.QWidget()
        self.tab_detect.setObjectName("tab_detect")
        
        # 为检测标签页设置主布局
        self.tab_detect_layout = QtWidgets.QHBoxLayout(self.tab_detect)
        self.tab_detect_layout.setContentsMargins(10, 10, 10, 10)
        
        # 左侧布局（图像显示和检测结果）
        self.left_layout = QtWidgets.QVBoxLayout()
        
        self.frame_2 = QtWidgets.QFrame(self.tab_detect)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        # 为frame_2设置布局
        self.frame2_layout = QtWidgets.QVBoxLayout(self.frame_2)
        self.frame2_layout.setContentsMargins(0, 0, 0, 0)
        
        self.label_show = QtWidgets.QLabel(self.frame_2)
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.label_show.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.label_show.setScaledContents(True)
        
        self.frame2_layout.addWidget(self.label_show)
        
        self.frame_3 = QtWidgets.QFrame(self.tab_detect)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        # 为frame_3设置布局
        self.frame3_layout = QtWidgets.QVBoxLayout(self.frame_3)
        self.frame3_layout.setContentsMargins(0, 10, 0, 10)
        
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        
        # 为groupBox_3设置布局
        self.groupBox3_layout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.groupBox3_layout.setContentsMargins(10, 10, 10, 10)
        
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        # 设置表格列宽自适应
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        
        self.groupBox3_layout.addWidget(self.tableWidget)
        self.frame3_layout.addWidget(self.groupBox_3)
        
        # 右侧控制面板
        self.frame_4 = QtWidgets.QFrame(self.tab_detect)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        # 为frame_4设置布局
        self.frame4_layout = QtWidgets.QVBoxLayout(self.frame_4)
        self.frame4_layout.setContentsMargins(10, 10, 10, 10)
        self.frame4_layout.setSpacing(10)
        
        # 添加控件到布局
        self.left_layout.addWidget(self.frame_2, 2)
        self.left_layout.addWidget(self.frame_3, 1)
        
        self.tab_detect_layout.addLayout(self.left_layout, 2)
        self.tab_detect_layout.addWidget(self.frame_4, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        
        # 为groupBox设置布局
        self.groupBox_layout = QtWidgets.QVBoxLayout(self.groupBox)
        self.groupBox_layout.setContentsMargins(10, 10, 10, 10)
        self.groupBox_layout.setSpacing(10)
        
        # 图片选择行
        self.pic_layout = QtWidgets.QHBoxLayout()
        self.PicBtn = QtWidgets.QPushButton(self.groupBox)
        self.PicBtn.setFixedSize(32, 32)
        self.PicBtn.setStyleSheet("border-image: url(:/icons/ui_imgs/icons/img.png);")
        self.PicBtn.setText("")
        self.PicBtn.setObjectName("PicBtn")
        
        self.PiclineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PiclineEdit.setInputMask("")
        self.PiclineEdit.setObjectName("PiclineEdit")
        
        self.FilesBtn = QtWidgets.QPushButton(self.groupBox)
        self.FilesBtn.setFixedSize(32, 32)
        self.FilesBtn.setStyleSheet("border-image: url(:/icons/ui_imgs/icons/folder.png);")
        self.FilesBtn.setText("")
        self.FilesBtn.setObjectName("FilesBtn")
        
        self.pic_layout.addWidget(self.PicBtn)
        self.pic_layout.addWidget(self.PiclineEdit)
        self.pic_layout.addWidget(self.FilesBtn)
        
        # 视频选择行
        self.video_layout = QtWidgets.QHBoxLayout()
        self.VideoBtn = QtWidgets.QPushButton(self.groupBox)
        self.VideoBtn.setFixedSize(32, 32)
        self.VideoBtn.setStyleSheet("border-image: url(:/icons/ui_imgs/icons/video.png);")
        self.VideoBtn.setText("")
        self.VideoBtn.setObjectName("VideoBtn")
        
        self.VideolineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.VideolineEdit.setObjectName("VideolineEdit")
        
        self.video_layout.addWidget(self.VideoBtn)
        self.video_layout.addWidget(self.VideolineEdit)
        
        # 摄像头选择行
        self.cap_layout = QtWidgets.QHBoxLayout()
        self.CapBtn = QtWidgets.QPushButton(self.groupBox)
        self.CapBtn.setFixedSize(32, 32)
        self.CapBtn.setStyleSheet("border-image: url(:/icons/ui_imgs/icons/camera.png);")
        self.CapBtn.setText("")
        self.CapBtn.setObjectName("CapBtn")
        
        self.CaplineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CaplineEdit.setObjectName("CaplineEdit")
        
        self.cap_layout.addWidget(self.CapBtn)
        self.cap_layout.addWidget(self.CaplineEdit)
        
        # 模型选择行
        self.model_layout = QtWidgets.QHBoxLayout()
        self.label_model = QtWidgets.QLabel(self.groupBox)
        self.label_model.setObjectName("label_model")
        
        self.comboBox_model = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_model.setObjectName("comboBox_model")
        
        self.model_layout.addWidget(self.label_model)
        self.model_layout.addWidget(self.comboBox_model)
        
        # 添加到groupBox布局
        self.groupBox_layout.addLayout(self.pic_layout)
        self.groupBox_layout.addLayout(self.video_layout)
        self.groupBox_layout.addLayout(self.cap_layout)
        self.groupBox_layout.addLayout(self.model_layout)
        
        # 添加到frame4布局
        self.frame4_layout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        
        # 为groupBox_2设置布局
        self.groupBox2_layout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.groupBox2_layout.setContentsMargins(10, 10, 10, 10)
        self.groupBox2_layout.setSpacing(10)
        
        # 顶部信息行
        self.top_info_layout = QtWidgets.QHBoxLayout()
        
        self.time_layout = QtWidgets.QHBoxLayout()
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.time_lb = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.time_lb.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.time_lb.setFont(font)
        self.time_lb.setText("")
        self.time_lb.setObjectName("time_lb")
        self.time_layout.addWidget(self.label_10)
        self.time_layout.addWidget(self.time_lb)
        
        self.nums_layout = QtWidgets.QHBoxLayout()
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.label_nums = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_nums.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_nums.setFont(font)
        self.label_nums.setText("")
        self.label_nums.setObjectName("label_nums")
        self.nums_layout.addWidget(self.label)
        self.nums_layout.addWidget(self.label_nums)
        
        self.top_info_layout.addLayout(self.time_layout)
        self.top_info_layout.addStretch(1)
        self.top_info_layout.addLayout(self.nums_layout)
        
        # 中间信息行
        self.middle_info_layout = QtWidgets.QHBoxLayout()
        
        self.combo_layout = QtWidgets.QHBoxLayout()
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.combo_layout.addWidget(self.label_5)
        self.combo_layout.addWidget(self.comboBox)
        
        self.middle_info_layout.addLayout(self.combo_layout)
        
        # 底部信息行
        self.bottom_info_layout = QtWidgets.QHBoxLayout()
        
        self.type_layout = QtWidgets.QHBoxLayout()
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_13.setObjectName("label_13")
        self.type_lb = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.type_lb.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.type_lb.setFont(font)
        self.type_lb.setText("")
        self.type_lb.setObjectName("type_lb")
        self.type_layout.addWidget(self.label_13)
        self.type_layout.addWidget(self.type_lb)
        
        self.conf_layout = QtWidgets.QHBoxLayout()
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.label_conf = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_conf.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_conf.setFont(font)
        self.label_conf.setText("")
        self.label_conf.setObjectName("label_conf")
        self.conf_layout.addWidget(self.label_11)
        self.conf_layout.addWidget(self.label_conf)
        
        self.bottom_info_layout.addLayout(self.type_layout)
        self.bottom_info_layout.addStretch(1)
        self.bottom_info_layout.addLayout(self.conf_layout)
        
        # 目标位置信息
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        
        # 坐标信息网格
        self.coords_layout = QtWidgets.QGridLayout()
        
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        
        self.label_xmin = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_xmin.setFont(font)
        self.label_xmin.setText("")
        self.label_xmin.setObjectName("label_xmin")
        
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        
        self.label_ymin = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ymin.setFont(font)
        self.label_ymin.setText("")
        self.label_ymin.setObjectName("label_ymin")
        
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        
        self.label_xmax = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmax.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_xmax.setFont(font)
        self.label_xmax.setText("")
        self.label_xmax.setObjectName("label_xmax")
        
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        
        self.label_ymax = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymax.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ymax.setFont(font)
        self.label_ymax.setText("")
        self.label_ymax.setObjectName("label_ymax")
        
        self.coords_layout.addWidget(self.label_6, 0, 0)
        self.coords_layout.addWidget(self.label_xmin, 0, 1)
        self.coords_layout.addWidget(self.label_8, 0, 2)
        self.coords_layout.addWidget(self.label_ymin, 0, 3)
        self.coords_layout.addWidget(self.label_7, 1, 0)
        self.coords_layout.addWidget(self.label_xmax, 1, 1)
        self.coords_layout.addWidget(self.label_9, 1, 2)
        self.coords_layout.addWidget(self.label_ymax, 1, 3)
        
        # 添加到groupBox_2布局
        self.groupBox2_layout.addLayout(self.top_info_layout)
        self.groupBox2_layout.addLayout(self.middle_info_layout)
        self.groupBox2_layout.addLayout(self.bottom_info_layout)
        self.groupBox2_layout.addWidget(self.label_4)
        self.groupBox2_layout.addLayout(self.coords_layout)
        
        # 添加到frame4布局
        self.frame4_layout.addWidget(self.groupBox_2)
        
        # 操作按钮组
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        
        # 为groupBox_4设置布局
        self.groupBox4_layout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.groupBox4_layout.setContentsMargins(20, 20, 20, 20)
        self.groupBox4_layout.setSpacing(40)
        
        self.SaveBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.SaveBtn.setFixedSize(151, 51)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ui_imgs/icons/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveBtn.setIcon(icon1)
        self.SaveBtn.setIconSize(QtCore.QSize(30, 30))
        self.SaveBtn.setObjectName("SaveBtn")
        
        self.ExitBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.ExitBtn.setFixedSize(151, 51)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ui_imgs/icons/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitBtn.setIcon(icon2)
        self.ExitBtn.setIconSize(QtCore.QSize(30, 30))
        self.ExitBtn.setObjectName("ExitBtn")
        
        # 添加到groupBox_4布局
        self.groupBox4_layout.addStretch(1)
        self.groupBox4_layout.addWidget(self.SaveBtn)
        self.groupBox4_layout.addWidget(self.ExitBtn)
        self.groupBox4_layout.addStretch(1)
        
        # 添加到frame4布局
        self.frame4_layout.addWidget(self.groupBox_4)
        self.frame4_layout.addStretch(1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        
        # 为frame_5设置布局
        self.frame5_layout = QtWidgets.QVBoxLayout(self.frame_5)
        self.frame5_layout.setContentsMargins(0, 0, 0, 0)
        
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        
        # 底部标签布局
        self.bottom_label_layout = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        
        # 添加控件到布局
        self.bottom_label_layout.addWidget(self.label_2)
        self.bottom_label_layout.addStretch(1)
        self.bottom_label_layout.addWidget(self.label_12)
        
        self.frame5_layout.addWidget(self.label_3)
        self.frame5_layout.addLayout(self.bottom_label_layout)
        
        # 将frame_5和tabWidget添加到主布局
        self.main_layout.addWidget(self.frame_5)
        self.main_layout.addWidget(self.tabWidget, 1)
        
        # 训练标签页
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        
        # 为训练标签页设置主布局
        self.tab_train_layout = QtWidgets.QVBoxLayout(self.tab_train)
        self.tab_train_layout.setContentsMargins(20, 20, 20, 20)
        self.tab_train_layout.setSpacing(20)
        
        # 数据集设置
        self.groupBox_data = QtWidgets.QGroupBox(self.tab_train)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_data.setFont(font)
        self.groupBox_data.setObjectName("groupBox_data")
        
        # 为groupBox_data设置布局
        self.groupBox_data_layout = QtWidgets.QVBoxLayout(self.groupBox_data)
        self.groupBox_data_layout.setContentsMargins(20, 20, 20, 20)
        self.groupBox_data_layout.setSpacing(15)
        
        # 数据集路径行
        self.data_path_layout = QtWidgets.QHBoxLayout()
        self.label_data_path = QtWidgets.QLabel(self.groupBox_data)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_data_path.setFont(font)
        self.label_data_path.setObjectName("label_data_path")
        
        self.lineEdit_data_path = QtWidgets.QLineEdit(self.groupBox_data)
        self.lineEdit_data_path.setPlaceholderText("请选择数据集配置文件")
        self.lineEdit_data_path.setObjectName("lineEdit_data_path")
        
        self.pushButton_browse = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_browse.setFixedSize(100, 30)
        self.pushButton_browse.setObjectName("pushButton_browse")
        
        self.data_path_layout.addWidget(self.label_data_path)
        self.data_path_layout.addWidget(self.lineEdit_data_path)
        self.data_path_layout.addWidget(self.pushButton_browse)
        
        # 上传按钮行
        self.upload_layout = QtWidgets.QHBoxLayout()
        self.pushButton_upload_images = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_upload_images.setFixedSize(150, 40)
        self.pushButton_upload_images.setObjectName("pushButton_upload_images")
        
        self.pushButton_upload_folder = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_upload_folder.setFixedSize(150, 40)
        self.pushButton_upload_folder.setObjectName("pushButton_upload_folder")
        
        self.upload_layout.addWidget(self.pushButton_upload_images)
        self.upload_layout.addWidget(self.pushButton_upload_folder)
        self.upload_layout.addStretch(1)
        
        # 添加到groupBox_data布局
        self.groupBox_data_layout.addLayout(self.data_path_layout)
        self.groupBox_data_layout.addLayout(self.upload_layout)
        
        # 训练配置
        self.groupBox_config = QtWidgets.QGroupBox(self.tab_train)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_config.setFont(font)
        self.groupBox_config.setObjectName("groupBox_config")
        
        # 为groupBox_config设置布局
        self.groupBox_config_layout = QtWidgets.QVBoxLayout(self.groupBox_config)
        self.groupBox_config_layout.setContentsMargins(20, 20, 20, 20)
        self.groupBox_config_layout.setSpacing(15)
        
        # 第一行配置
        self.config_row1 = QtWidgets.QHBoxLayout()
        self.label_model_type = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_model_type.setFont(font)
        self.label_model_type.setObjectName("label_model_type")
        
        self.comboBox_model_type = QtWidgets.QComboBox(self.groupBox_config)
        self.comboBox_model_type.setFixedSize(200, 35)
        self.comboBox_model_type.setObjectName("comboBox_model_type")
        
        self.label_epochs = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_epochs.setFont(font)
        self.label_epochs.setObjectName("label_epochs")
        
        self.spinBox_epochs = QtWidgets.QSpinBox(self.groupBox_config)
        self.spinBox_epochs.setFixedSize(100, 30)
        self.spinBox_epochs.setMinimum(1)
        self.spinBox_epochs.setMaximum(1000)
        self.spinBox_epochs.setObjectName("spinBox_epochs")
        
        self.config_row1.addWidget(self.label_model_type)
        self.config_row1.addWidget(self.comboBox_model_type)
        self.config_row1.addWidget(self.label_epochs)
        self.config_row1.addWidget(self.spinBox_epochs)
        self.config_row1.addStretch(1)
        
        # 第二行配置
        self.config_row2 = QtWidgets.QHBoxLayout()
        self.label_batch = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_batch.setFont(font)
        self.label_batch.setObjectName("label_batch")
        
        self.spinBox_batch = QtWidgets.QSpinBox(self.groupBox_config)
        self.spinBox_batch.setFixedSize(100, 30)
        self.spinBox_batch.setMinimum(1)
        self.spinBox_batch.setMaximum(128)
        self.spinBox_batch.setObjectName("spinBox_batch")
        
        self.label_lr = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_lr.setFont(font)
        self.label_lr.setObjectName("label_lr")
        
        self.lineEdit_lr = QtWidgets.QLineEdit(self.groupBox_config)
        self.lineEdit_lr.setFixedSize(100, 30)
        self.lineEdit_lr.setPlaceholderText("0.01")
        self.lineEdit_lr.setObjectName("lineEdit_lr")
        
        self.label_img_size = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_img_size.setFont(font)
        self.label_img_size.setObjectName("label_img_size")
        
        self.spinBox_img_size = QtWidgets.QSpinBox(self.groupBox_config)
        self.spinBox_img_size.setFixedSize(100, 30)
        self.spinBox_img_size.setMinimum(320)
        self.spinBox_img_size.setMaximum(1280)
        self.spinBox_img_size.setSingleStep(32)
        self.spinBox_img_size.setObjectName("spinBox_img_size")
        
        self.config_row2.addWidget(self.label_batch)
        self.config_row2.addWidget(self.spinBox_batch)
        self.config_row2.addWidget(self.label_lr)
        self.config_row2.addWidget(self.lineEdit_lr)
        self.config_row2.addWidget(self.label_img_size)
        self.config_row2.addWidget(self.spinBox_img_size)
        self.config_row2.addStretch(1)
        
        # 第三行配置
        self.config_row3 = QtWidgets.QHBoxLayout()
        self.label_device = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_device.setFont(font)
        self.label_device.setObjectName("label_device")
        
        self.comboBox_device = QtWidgets.QComboBox(self.groupBox_config)
        self.comboBox_device.setFixedSize(200, 30)
        self.comboBox_device.setObjectName("comboBox_device")
        
        self.label_val_interval = QtWidgets.QLabel(self.groupBox_config)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_val_interval.setFont(font)
        self.label_val_interval.setObjectName("label_val_interval")
        
        self.spinBox_val_interval = QtWidgets.QSpinBox(self.groupBox_config)
        self.spinBox_val_interval.setFixedSize(100, 30)
        self.spinBox_val_interval.setMinimum(1)
        self.spinBox_val_interval.setMaximum(100)
        self.spinBox_val_interval.setObjectName("spinBox_val_interval")
        
        self.config_row3.addWidget(self.label_device)
        self.config_row3.addWidget(self.comboBox_device)
        self.config_row3.addWidget(self.label_val_interval)
        self.config_row3.addWidget(self.spinBox_val_interval)
        self.config_row3.addStretch(1)
        
        # 添加到groupBox_config布局
        self.groupBox_config_layout.addLayout(self.config_row1)
        self.groupBox_config_layout.addLayout(self.config_row2)
        self.groupBox_config_layout.addLayout(self.config_row3)
        
        # 训练控制
        self.groupBox_train = QtWidgets.QGroupBox(self.tab_train)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        self.groupBox_train.setFont(font)
        self.groupBox_train.setObjectName("groupBox_train")
        
        # 为groupBox_train设置布局
        self.groupBox_train_layout = QtWidgets.QVBoxLayout(self.groupBox_train)
        self.groupBox_train_layout.setContentsMargins(20, 20, 20, 20)
        
        self.pushButton_train = QtWidgets.QPushButton(self.groupBox_train)
        self.pushButton_train.setFixedSize(200, 50)
        self.pushButton_train.setObjectName("pushButton_train")
        
        # 居中按钮
        self.button_center_layout = QtWidgets.QHBoxLayout()
        self.button_center_layout.addStretch(1)
        self.button_center_layout.addWidget(self.pushButton_train)
        self.button_center_layout.addStretch(1)
        
        self.groupBox_train_layout.addLayout(self.button_center_layout)
        
        # 状态和进度
        self.status_layout = QtWidgets.QVBoxLayout()
        self.label_status = QtWidgets.QLabel(self.tab_train)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        
        self.progressBar = QtWidgets.QProgressBar(self.tab_train)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        
        self.status_layout.addWidget(self.label_status)
        self.status_layout.addWidget(self.progressBar)
        
        # 添加到训练标签页布局
        self.tab_train_layout.addWidget(self.groupBox_data)
        self.tab_train_layout.addWidget(self.groupBox_config)
        self.tab_train_layout.addWidget(self.groupBox_train)
        self.tab_train_layout.addLayout(self.status_layout)
        
        # 添加标签页到标签页控件
        self.tabWidget.addTab(self.tab_detect, "")
        self.tabWidget.addTab(self.tab_train, "")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于yolov8的安全帽检查与识别系统"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检测结果与位置信息"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件路径"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "坐标位置"))
        self.groupBox.setTitle(_translate("MainWindow", "文件导入"))
        self.PiclineEdit.setPlaceholderText(_translate("MainWindow", "请选择图片文件"))
        self.VideolineEdit.setPlaceholderText(_translate("MainWindow", "请选择视频文件"))
        self.CaplineEdit.setPlaceholderText(_translate("MainWindow", "摄像头未开启"))
        self.label_model.setText(_translate("MainWindow", "检测模型:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "检测结果"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">目标位置：</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">xmin:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ymin：</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">xmax：</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ymax：</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">目标数目：</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">目标选择：</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">用时：</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">置信度：</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">类型：</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "操作"))
        self.SaveBtn.setText(_translate("MainWindow", "保存"))
        self.ExitBtn.setText(_translate("MainWindow", "退出"))
        self.label_3.setText(_translate("MainWindow", "基于yolov8的安全帽检查与识别系统"))
        # 设置标签页文本
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detect), _translate("MainWindow", "目标检测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "模型训练"))
        # 训练标签页文本
        self.groupBox_data.setTitle(_translate("MainWindow", "数据集设置"))
        self.label_data_path.setText(_translate("MainWindow", "数据集路径:"))
        self.pushButton_browse.setText(_translate("MainWindow", "浏览"))
        self.pushButton_upload_images.setText(_translate("MainWindow", "上传图片"))
        self.pushButton_upload_folder.setText(_translate("MainWindow", "上传文件夹"))
        self.groupBox_config.setTitle(_translate("MainWindow", "训练配置"))
        self.label_model_type.setText(_translate("MainWindow", "模型类型:"))
        self.label_epochs.setText(_translate("MainWindow", "训练轮数:"))
        self.label_batch.setText(_translate("MainWindow", "批次大小:"))
        self.label_lr.setText(_translate("MainWindow", "学习率:"))
        self.label_img_size.setText(_translate("MainWindow", "图片大小:"))
        self.label_device.setText(_translate("MainWindow", "设备选择:"))
        self.label_val_interval.setText(_translate("MainWindow", "验证间隔:"))
        self.groupBox_train.setTitle(_translate("MainWindow", "训练控制"))
        self.pushButton_train.setText(_translate("MainWindow", "开始训练"))
        self.label_status.setText(_translate("MainWindow", "状态: 就绪"))
import ui_sources_rc
